# Config files mounted in /usr/share/cassandra/conf
# (it cannot be mounted in /etc/cassandra because chowned to cassandra in the docker-entrypoint.sh)
{{- if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elassandra.fullname" . }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "elassandra.name" . }}
    chart: {{ template "elassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
{{- range $key, $val := .Values.configs }}
  {{ $key }}: |-
{{  $val | indent 4 }}
{{- end }}
{{- end }}
